menu:main.o Menu.o Music.o Text.o Buttons.o Background.o time.o map.o pres.o collisionparfaite.o xo.o
	gcc main.o Menu.o Music.o Text.o Buttons.o Background.o time.o map.o pres.o collisionparfaite.o xo.o -o menu -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf -g
main.o:main.c
	gcc -c main.c -g
Menu.o:Menu.c
	gcc -c Menu.c -g
Music.o:Music.c
	gcc -c Music.c -g
Text.o:Text.c
	gcc -c Text.c -g
Buttons.o:Buttons.c
	gcc -c Buttons.c -g
Background.o:Background.c
	gcc -c Background.c -g
time.o:time.c 
	gcc -c time.c -g
map.o:map.c
	gcc -c map.c -g 
pres.o:pres.c
	gcc -c pres.c -g
collisionparfaite.o:collisionparfaite.c
	gcc -c collisionparfaite.c -g
xo.o:xo.c
	gcc -c xo.c -g

